/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Phone;
import javax.swing .*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
/**
 *
 * @author Lenovo
 */
public class CreateGroups {
    

    /**
     * Creates new form CreateGroups
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents(String file) {
        Delete d = new Delete();
        d.GroupString(file);
        d.deleteDelete(-1);
    }
    // </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      //  new CreateGroups();

        }
        }
