/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Phone;

import java.util.LinkedList;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author AmratKukreje
 */
public class Edit {
  JFrame frame;  
  String str;
  LinkedList<String> temp;

  /**
   * Creates new form Edit
   */
  
  public void edit() {
    DisplayGroups d = new DisplayGroups();
    d.displaygroup(-4);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  public LinkedList<String> setTextfield(String str) {
    LinkedList<String> temp = new LinkedList<>();
    String str1 = "";
    for (int i = 0; i < str.length(); i++) {
      if (str.charAt(i) != ' ') {
        str1 += str.charAt(i);
      }
      if (str.charAt(i) == ' ' || i == str.length() - 1) {
        temp.add(str1);
        str1 = "";
      }
    }
    return temp;
  }

  /**
 * @param str
 */
public void initComponents(String str,JFrame f1) {
   f1.setVisible(false);
   
    
    this.str = str;
    temp = setTextfield(str);
    frame = new JFrame();
    jLabel1 = new JLabel();
    jButton1 = new JButton();
    jLabel2 = new JLabel();
    jLabel3 = new JLabel();
    jLabel4 = new JLabel();
    jTextField1 = new JTextField(temp.get(0));
    jTextField2 = new JTextField(temp.get(1));
    jTextField3 = new JTextField(temp.get(2));
    jButton2 = new JButton();

    frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
    jLabel1.setText("                                   Edit Contacts");
    jLabel1.setBorder(
      BorderFactory.createMatteBorder(
        2,
        2,
        2,
        2,
        new java.awt.Color(0, 0, 0)
      )
    );

    jButton1.setBackground(new java.awt.Color(0, 102, 153));
    jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setText("Edit");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setText("First name");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel3.setText("Last name");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel4.setText("Phone No :");

    jTextField2.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jTextField2ActionPerformed(evt);
        }
      }
    );

    jButton2.setBackground(new java.awt.Color(0, 102, 153));
    jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("Close");
    jButton2.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton2ActionPerformed(evt);
        }
      }
    );

    GroupLayout layout = new GroupLayout(
      frame.getContentPane()
    );
    frame.getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(GroupLayout.Alignment.LEADING)
        .addComponent(
          jLabel1,
          GroupLayout.Alignment.TRAILING,
          GroupLayout.DEFAULT_SIZE,
          325,
          Short.MAX_VALUE
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(
                      layout
                        .createParallelGroup(
                          GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                    )
                    .addGap(54, 54, 54)
                    .addGroup(
                      layout
                        .createParallelGroup(
                          GroupLayout.Alignment.LEADING,
                          false
                        )
                        .addComponent(
                          jTextField1,
                          GroupLayout.DEFAULT_SIZE,
                          86,
                          Short.MAX_VALUE
                        )
                        .addComponent(jTextField2)
                        .addComponent(jTextField3)
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(
                      jButton1,
                      GroupLayout.PREFERRED_SIZE,
                      86,
                      GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(58, 58, 58)
                    .addComponent(
                      jButton2,
                      GroupLayout.DEFAULT_SIZE,
                      86,
                      Short.MAX_VALUE
                    )
                )
            )
            .addGap(62, 62, 62)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addComponent(
              jLabel1,
              GroupLayout.DEFAULT_SIZE,
              28,
              Short.MAX_VALUE
            )
            .addPreferredGap(
              LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(
                  jTextField1,
                  GroupLayout.DEFAULT_SIZE,
                  28,
                  Short.MAX_VALUE
                )
            )
            .addPreferredGap(
              LayoutStyle.ComponentPlacement.RELATED,
              23,
              Short.MAX_VALUE
            )
            .addGroup(
              layout
                .createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(
                  jTextField2,
                  GroupLayout.PREFERRED_SIZE,
                  28,
                  GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(21, 21, 21)
            .addGroup(
              layout
                .createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(
                  jTextField3,
                  GroupLayout.PREFERRED_SIZE,
                  30,
                  GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(24, 24, 24)
            .addGroup(
              layout
                .createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(
                  jButton1,
                  GroupLayout.PREFERRED_SIZE,
                  31,
                  GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jButton2,
                  GroupLayout.PREFERRED_SIZE,
                  31,
                  GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap()
        )
    );
    frame.setVisible(true);
    frame.pack();
  } // </editor-fold>

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    Directory d = new Directory();
    String name = "";
    if (evt.getSource() == jButton1) {
      temp.removeAll(temp);
      name =
        jTextField1.getText() +
        " " +
        jTextField2.getText() +
        " " +
        jTextField3.getText();
      d.updateNum(str, name);
      int res = JOptionPane.showConfirmDialog(
        frame,
        "Sure? You want to Edit?",
        "Swing Tester",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
      );
      if (res == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(null, "Contact was Edited!");
        frame.setVisible(false);    
    }
    }
  }

  private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    Edit e = new Edit();
    e.edit();
  }

  // Variables declaration - do not modify
  private JButton jButton1;
  private JButton jButton2;
  private JLabel jLabel1;
  private JLabel jLabel2;
  private JLabel jLabel3;
  private JLabel jLabel4;
  private JTextField jTextField1;
  private JTextField jTextField2;
  private JTextField jTextField3;
  // End of variables declaration

}
